blog/urls.py
from django.urls import path
from . import views
from .views import PostCreatView, PostUpdateView, PostDeleteView


app_name = 'blog'


urlpatterns =[
    
    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('detail/<int:post_id>/', views.post_detail, name='detail'),
    path('new_post/', PostCreatView.as_view(), name='new_post'),
    path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('user.urls', namespace='user')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    #path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('login/', views.login_user, name='login'),
    #path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.Logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Post(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()
    post_date = models.DateTimeField(default=timezone.now)
    post_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.pk])
    
    class Meta:

        ordering = ('-post_date',)
        verbose_name = ("Post")
        verbose_name_plural = ("Posts")

#===============================================================

class Comment(models.Model):

    name = models.CharField(max_length=50, verbose_name="الاسم")
    email = models.EmailField(verbose_name='البريد الالكتروني')
    body = models.TextField(verbose_name='التعليق')
    comment_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    class Meta:
        
        ordering = ('-comment_date',)
        verbose_name = ("Comment")
        verbose_name_plural = ("Comments")

    def __str__(self):
        return 'علق {} على {}.' .format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment, Post

class NewComment(forms.ModelForm):
    
    class Meta:
        
        model = Comment
        fields = ('name', 'email', 'body')
        
class PostCreatForm(forms.ModelForm):
    
    title = forms.CharField(label='عنوان التدوينة')
    content = forms.CharField(label='نص التدوينة', widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ['title', 'content']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import NewComment, PostCreatForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.

def home(request):
    
    posts = Post.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_page)    
    context = {
        'title': 'الصفحة الرئيسية',
        'posts': posts,
        'page' : page,
    }
    return render(request, 'blog/index.html', context)

#====================================================

def about(request):
    context = {
        'title': 'من أنا',
    }
    return render(request, 'blog/about.html', context)

#=====================================================

def post_detail(request, post_id):
    
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.filter(active=True)
    if request.method =='POST':
        comment_form = NewComment(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form = NewComment()
    else:
        comment_form = NewComment()
    context = {
        'title': post.title, 
        'post' : post,
        'comments' : comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/detail.html', context)

#========================================================


class PostCreatView(LoginRequiredMixin, CreateView):
    
    model = Post
    # fields = ['title', 'content']
    template_name = 'blog/new_post.html'
    form_class = PostCreatForm
    
    
    def form_valid(self, form):
        
        form.instance.author = self.request.user
        return super().form_valid(form)
    
#===========================================================


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = Post
    template_name = 'blog/post_update.html'
    form_class = PostCreatForm

    def form_valid(self, form):

        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

#=========================================================================


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    model = Post
    success_url = '/'
    
    def test_func(self):

        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<h3 class="border-bottom">من أنا</h3>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
{% load post_tag %}

<!DOCTYPE html>
<html lang="ar">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    {% if title %}
    <title>مدونة | {{ title }}</title>
    {% else %}
    <title>مدونة</title>
    {% endif %}
    
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}" />
    <link rel="shortcut icon" href="{% static 'blog/images/favicon.ico' %}" />
    
  </head>
  <body>
    <header>
      <!-- start Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
          <img class="rounded-circle border" src="{% static 'blog/images/mim.png' %}" alt="شعار" width="35px">
          مدونة</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:home' %}"
                >الرئيسية <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                دوراتي
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">دورة بايثون</a>
                <a class="dropdown-item" href="#">دورة دجانجو</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">دورة ويندوز</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">من أنا</a>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:new_post' %}">تدوينة جديدة</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:profile' %}">الملف الشخصي</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">تسجيل الخروج</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">تسجيل الدخول</a>
            </li>
            
            <li class="nav-item"><a class="nav-link" href="{% url 'user:register' %}">تسجيل</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <!-- End Navbar -->
    </header>
    <section class="">
      <div class="container">
        <div class="row mt-4">
          <div class="col-md-8">
            {% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
{% endfor %}
{% endif %}
           {% block content %}
           
           {% endblock content %}
          </div>
          <div class="col-md-4">
            <div class="card mb-3">
              <h3 class="text-center bg-secondary text-light p-2">آخر التدوينات</h3>
              {% latest_posts %}
            </div>
            <div class="card mb-3">
              <h3 class="text-center bg-secondary text-light p-2">آخر التعليقات</h3>
              {% latest_comments %}
              <!-- <ul class="list-group-flush latest-comment">
              <li class="list-group-item latest-comment-item"><a href="#" class="text-dark">التعليق الأول</a></li>
              <li class="list-group-item latest-comment-item"><a href="#" class="text-dark">التعليق الثاني</a></li>
              <li class="list-group-item latest-comment-item"><a href="#" class="text-dark">التعليق الثالث</a></li>
              <li class="list-group-item latest-comment-item"><a href="#" class="text-dark">التعليق الرابع</a></li>
              <li class="list-group-item latest-comment-item"><a href="#" class="text-dark">التعليق الخامس</a></li>
              </ul> -->
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- start footer -->
    <footer class="bg-secondary">
      <div class="container-fluid">
      <div class="row">
        <div class="col-md">
          <div class="card-group mt-3">
            <div class="card m-3">
              <h3 class="card-title text-center border-bottom p-2 m-3">من أنا</h3>
              <div class="card-body">
                <div class="text-center">
                <img src="{% static 'blog/images/mim.png' %}" alt="شعار" width="100px">
                </div>
                  من أنا نص تجريبي  من أنا نص تجريبي من أنا نص تجريبي من أنا نص تجريبي من أنا نص تجريبي من أنا نص تجريبي من أنا نص تجريبي من أنا نص تجريبي من أنا نص تجريبي ر من أنا نص تجريبي من أنا نص تجريبي
              </div>
            </div>
              <div class="card m-3">
              <h3 class="card-title text-center border-bottom p-2 m-3">مواقع هامة</h3>
              <div class="card-body">
                <ul>
                  <li><a href="#">الموقع الأول</a></li>
                  <li><a href="#">الموقع الثاني</a></li>
                  <li><a href="#">الموقع الثالث</a></li>
                  <li><a href="#">الموقع الرابع</a></li>
                </ul>
              </div>
            </div>
              <div class="card m-3">
              <h3 class="card-title text-center border-bottom p-2 m-3">وسائل التواصل الاجتماعي</h3>
              <h4 class="card-body text-center">
                <ul>
                 <a class="text-secondary" href="#"><li class="fab fa-facebook"></li></a>
                 <a class="text-secondary" href="#"><li class="fab fa-twitter"></li></a>
                 <a class="text-secondary" href="#"><li class="fab fa-instagram"></li></a>
                 <a class="text-secondary" href="#"><li class="fab fa-linkedin"></li></a>
                 <a class="text-secondary" href="#"><li class="fab fa-youtube"></li></a>
                 <a class="text-secondary" href="#"><li class="fab fa-telegram"></li></a>
                </ul>
              </h4>
            </div>
          </div>
        </div>
      </div>
      <div class="row p-2">
        <div class="col-md text-center">
        <small class="text-light">&copy;جميع الحقوق محفوظة</small>
        </div>
      </div>
      </div>
    </footer>
    <!-- End footer -->

    <script type="" src="{% static 'blog/js/jquery-3.3.1.slim.min.js' %}"></script>
    <script type="" src="{% static 'blog/js/popper.min' %}"></script>
    <script type="" src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script
      type=""
      src="{% static 'blog/js/fontawesome-all.min.js' %}"
    ></script>
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border mb-3 p-3">
        <img class="img-fluid rounded-circle border m-2" style="width: 120px; height: 120px;" src="{{user.profile.image.url}}" alt="صورة الناشر" />
        <span class="text-secondary">نشر في {{post.post_date|date:'d-m-Y'}}</span>
        {% if post.author == user %}
        <div class="form-group btn-editing">
            <a href="{% url 'blog:update_post' post.id %}" class="btn btn-secondary">تحرير</a>
            <a class="btn btn-danger" href="{% url 'blog:delete_post' post.id %}">حذف</a>
        </div>
        {% endif %}
        <h3><a class="text-dark">{{ post.title }}</a></h3>
        <p>{{ post.content }}</p>
    </div>
    <div class="">
        <h2 class="border-bottom mt-5 mb-3">التعليقات({{comments.count}})</h2>
        {% for comment in comments %}
        <ul class="p-3 comment">
            <h6 class="border-bottom p-2">( {{ comment.name}} ) <span class="text-secondary">
                {{comment.comment_date|date:'d-m-Y'}}
            </span></h6>
            {{ comment.body }}
        </ul>
        
        {% empty %}
            <h5 class="text-center p-4 comment">لاتوجد تعليقات.</h5>
        {% endfor %}
    </div>
    <h3 class="border-bottom pb-3 mb-3 mt-5">إضافة تعليق جديد</h3>
    <div class="border p-4 mb-5 mt-4">
    <form method="POST">
        {% csrf_token %}
        {{comment_form|crispy}}
        <input class="btn btn-secondary" value=" نشر التعليق" type="submit">
    </form>
    </div>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

 {% for post in posts %}
    <div class="border mb-3 p-3">
        {% if post.author.profile.image %}
        
     
        <img class="img-fluid rounded-circle border m-2" width="70px" src="{{post.author.profile.image.url}}" alt="صورة الناشر" />
        {% else %}
        <img class="img-fluid rounded-circle border m-2" width="70px" src="blog\static\blog\images\man-person-icon.png" alt="صورة الناشر" />  
        {% endif %}
        <span class="text-secondary">نشر في {{post.post_date|date:'d-m-Y'}}</span>
        <h3><a class="text-dark" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h3>
        <p>{{ post.content }}</p>

    </div>
 {% endfor %}
 {% include 'blog/pagination.html' with page=posts%}
{% endblock content %}

blog/templates/blog/latest_comments.html
<ul class="list-group-flush latest-comment">
    {% for comment in l_comments %}
        <a href="{% url 'blog:detail' comment.post.id %}" class="text-dark">
            <li class="list-group-item latest-comment-item">
                {{ comment }}</li>
        </a>
        {% empty %}
        <li class="list-group-item latest-comment-item">لا يوجد تعليقات</li>
    {% endfor %}
</ul>

blog/templates/blog/latest_posts.html
<ul class="list-group-flush latest-post">
    {% for post in l_posts %}
        <a href="{% url 'blog:detail' post.id %}" class="text-dark">
            <li class="list-group-item latest-post-item">
                {{ post.title }}</li>
        </a>
    {% endfor %}
</ul>

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">تدوينة جديدة</legend>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-secondary mt-4" value="نشر" type="submit">
    </form>
    </div>
{% endblock content %}

blog/templates/blog/pagination.html
        <div class="pt-3 mt-4 mb-5 text-center">
            {% if page.has_next %}
            <a href="?page={{page.next_page_number}}" class="btn btn-secondary bg-secondary">التالي</a>
            {% else %}
            <a href="" class="btn btn-secondary bg-secondary disabled">التالي</a>
            {% endif %}

            <span class="pr-4 pl-4">صفحة {{page.number}} من {{page.paginator.num_pages}}</span>

            {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}" class="btn btn-secondary bg-secondary">السابق</a>
            {% else %}
            <a href="" class="btn btn-secondary bg-secondary disabled">السابق</a>
            {% endif %}
        </div>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">حذف التدوينة</legend>
    <form method="POST">
        <legend class="pb-1 mb-3 mt-4">هل أنت متأكد من حذف "{{object.title}}" ؟</legend>
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-danger mt-3" value="حذف" type="submit">
        <a href="{% url 'blog:detail' object.id %}" class="btn btn-secondary mt-3 back-btn">تراجع</a>
    </form>
    </div>
{% endblock content %}

blog/templates/blog/post_update.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">تحرير التدوينة</legend>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-secondary mt-4" value="تحديث" type="submit">
    </form>
    </div>
{% endblock content %}