blog/urls.py
from django.urls import path
from . import views
from .views import PostCreatView, PostUpdateView, PostDeleteView


app_name = 'blog'


urlpatterns =[
    
    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('detail/<int:post_id>/', views.post_detail, name='detail'),
    path('new_post/', PostCreatView.as_view(), name='new_post'),
    path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('user.urls', namespace='user')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    #path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('login/', views.login_user, name='login'),
    #path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.Logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from PIL import Image

# Create your models here.

class Profile(models.Model):

    image = models.ImageField(
        default='profile_pics/man-person-icon.png', upload_to='profile_pics')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Profile")
        verbose_name_plural = ("Profiles")

    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.width > 300 or img.height > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def create_profile(sender, **kwargs):
        
        if kwargs['created']:
            user_profile = Profile.objects.create(user=kwargs['instance'])
    post_save.connect(create_profile, User)
        

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserCreateForm(forms.ModelForm):
    
    username = forms.CharField(max_length=30, label="اسم المستخدم", help_text="اسم المستخدم يجب ألا يحتوي على مسافات.")
    email = forms.EmailField(label="البريد الالكتروني")
    first_name = forms.CharField(max_length=100, label="الاسم الأول")
    last_name = forms.CharField(max_length=100, label="الاسم الأخير")
    password1 = forms.CharField(min_length= 8, label="كلمة المرور", widget=forms.PasswordInput())
    password2 = forms.CharField(min_length=8, label="تأكيد كلمة المرور", widget=forms.PasswordInput())

    class Meta:

        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("كلمة المرور غير متطابقة")
        return cd['password2']

    def clean_username(self):
        
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError("اسم المستخدم موجود مسبقا")
        return cd['username']    

class LoginForm(forms.ModelForm):
    
    username = forms.CharField(label="اسم المستخدم")
    password = forms.CharField(label="كلمة المرور", widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'password')
        
class UserUpdateForm(forms.ModelForm):
    
    first_name = forms.CharField(max_length=100, label="الاسم الأول")
    last_name = forms.CharField(max_length=100, label="الاسم الأخير")
    email = forms.EmailField(label="البريد الالكتروني")
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        
class ProfileUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ('image',)

user/views.py
from django.shortcuts import redirect, render
from .forms import UserCreateForm, LoginForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from blog.models import Post
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.


def register(request):
    
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            username = form.save(commit=False)
            username.set_password(form.cleaned_data['password1'])
            #username = form.cleaned_data['username'] 
            username.save()
            messages.success(request,f'تهانينا {username} لقد تمت عملية التسجيل بنجاح')
            return redirect('user:login')
    else:
        form = UserCreateForm()
    
    context= {
        'title': 'التسجيل',
        'form' : form,
    }
    return render(request, 'user/register.html', context)

def login_user(request):
    
    if request.method == 'POST':
        form = LoginForm()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('user:profile')
        else:
            messages.warning(request, "هناك خطأ في اسم المستخدم أو كلمة المرور!")
        
    else:
        form = LoginForm()
    context = {
        'title': 'تسجيل الدخول',
        'form': form,
    }
    return render(request, 'user/login.html', context)

def Logout_user(request):
    logout(request)
    context = {
        'title': 'تسجيل الخروج'
    }
    return render(request, 'user/logout.html', context)

@login_required(login_url='user:login')
def profile(request):
    
    posts = Post.objects.filter(author=request.user)
    post_list = Post.objects.filter(author=request.user)
    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_page)
    context = {
        'title': 'الملف الشخصي',
        'posts': posts,
        'page' : page,
        'post_list': post_list,
    }
    return render(request, 'user/profile.html',context)


@login_required(login_url='user:login')
def profile_update(request):
    
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        user_form.save()
        profile_form.save()
        messages.success(request, 'تم تعديل الملف الشخصي بنجاح!')
        return redirect('user:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'title': 'تعديل الملف الشخصي',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    
    return render(request, 'user/profile_update.html', context)

user/templates/user/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">تسجيل الدخول</legend>
        
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-secondary mt-4" value="تسجيل الدخول" type="submit">
    </form>
    <div class="border-top mt-4 p-2">
        <small>إذا لم يكن لديك حساب من قبل يمكنك <a href="{% url 'user:register' %}">التسجيل هنا</a></small>
    </div>
    </div>
{% endblock content %}

user/templates/user/logout.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">تسجيل الخروج</legend>
<a href="{% url 'user:login' %}">تسجيل الدخول مرة أخرى</a>
    </div>
{% endblock content %}

user/templates/user/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<!-- {% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
{% endfor %}
{% endif %} -->
<div class="border p-4 mb-5">
    <div class="row">
        <div class="col-md-3 text-center">
             <img class="img-fluid rounded-circle border m-2" style="width: 120px; height: 120px;" src="{{user.profile.image.url}}" alt.url}}" alt="صورة الناشر" />
             <div class="mt-3">
             <a class="btn btn-secondary bg-secondary" href="{% url 'user:profile_update' %}"> <i class="fas fa-pen fa-xs"></i> تحرير</a>
            </div>
        </div>
        <div class="col-md-9">
            <h2 class="mb-4">{{user.username}}</h2>
            <p class="font-weight-bold">الاسم : <span class="font-weight-normal">{{user.first_name}} {{user.last_name}}</span></p>
            <p class="font-weight-bold">البريد الالكتروني : <span class="font-weight-normal">{{user.email}}</span></p>
        </div>
    </div>
</div>
<div class="row mb-5">
    <div class="col-md">
        <h3 class="border-bottom pb-3 mb-4">عدد التدوينات التي دونتها</h3>
        <h4 class="text-center bg-secondary p-4 text-light">{{posts.count}}</h4>
        <h3 class="border-bottom mb-4 mt-5 pb-3">تدويناتي</h3>
        {% for post in post_list %}
        <ul class="pr-2">
            <a class="text-dark" href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
        </ul>
        {% empty %}
        <h4 class="text-center mb-5">لا توجد تدوينات حتى الأن</h3>
        {% endfor %}
        {% include 'blog/pagination.html' with page=post_list%}

    </div>
</div>
{% endblock content %}

user/templates/user/profile_update.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">تعديل الملف الشخصي</legend>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{user_form|crispy}}
        <!-- {{profile_form|crispy}} -->
        <div>
            <span class="mb-2" style="display:block">صورة الملف الشخصي *</span>
            الصورة الحالية : <a href="{{user.profile.image.url}}">{{user.profile.image}}</a>
            <br>
            <label for="image" class= "btn btn-outline-secondary mt-2">اختيار الصورة</label>
            <input type="file" name="image" id="image" accept="image/*" style="display:none">
        </div>
        <input
         class="btn btn-secondary mt-4" value="تعديل" type="submit" href="{% url 'user:profile' %}"
         >
    </form>
    </div>
{% endblock content %}

user/templates/user/register.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="border p-4 mb-5">
        <legend class="border-bottom pb-1 mb-3">التسجيل</legend>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-secondary mt-4" value="تسجيل" type="submit">
    </form>
    <div class="border-top mt-4 p-2">
        <small>إذا كان لديك حساب من قبل يمكنك <a href="{% url 'user:login' %}">تسجيل الدخول</a></small>
    </div>
    </div>
{% endblock content %}